#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=3:
    print("Input format should be = ./chatclient ip:port nickname")
    sys.exit()

my_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

my_server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
