#!/usr/bin/python3
import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=2:
    print("Input format be = ./chatserver ip:port ")
    sys.exit()

my_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
my_server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

Info = (sys.argv[1])
a=Info.split(':')
IP_addr=str(a[0])
port=int(a[1])

my_server.bind((IP_addr,port))
my_server.listen(100)

print('Waiting for client connections')


clients=[]
clients.append(server)